version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
